# Generated by Django 4.0.6 on 2024-09-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornalindo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nome_usuario',
            field=models.CharField(default='nomessssssssssssss', max_length=30),
            preserve_default=False,
        ),
    ]
