# Generated by Django 4.0.6 on 2024-09-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornalindo', '0002_usuario_nome_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='edicao',
            name='nome',
            field=models.CharField(default='Primeira', max_length=50),
            preserve_default=False,
        ),
    ]
